name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: gulp build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: public_${{ github.run_number }}
          path: public
